// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fft_HW_Top_DataFlox (
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        in_r,
        out_r,
        num,
        ap_clk,
        ap_rst,
        out_r_ap_vld,
        ap_start,
        in_r_ap_vld,
        num_ap_vld,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [63:0] m_axi_gmem_WDATA;
output  [7:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [63:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [8:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [63:0] in_r;
input  [63:0] out_r;
input  [31:0] num;
input   ap_clk;
input   ap_rst;
input   out_r_ap_vld;
input   ap_start;
input   in_r_ap_vld;
input   num_ap_vld;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire    entry_proc_U0_start_out;
wire    entry_proc_U0_start_write;
wire   [63:0] entry_proc_U0_out_c_din;
wire    entry_proc_U0_out_c_write;
wire    load_nfft_value_U0_ap_start;
wire    load_nfft_value_U0_ap_done;
wire    load_nfft_value_U0_ap_continue;
wire    load_nfft_value_U0_ap_idle;
wire    load_nfft_value_U0_ap_ready;
wire    load_nfft_value_U0_start_out;
wire    load_nfft_value_U0_start_write;
wire    load_nfft_value_U0_m_axi_gmem_AWVALID;
wire   [63:0] load_nfft_value_U0_m_axi_gmem_AWADDR;
wire   [0:0] load_nfft_value_U0_m_axi_gmem_AWID;
wire   [31:0] load_nfft_value_U0_m_axi_gmem_AWLEN;
wire   [2:0] load_nfft_value_U0_m_axi_gmem_AWSIZE;
wire   [1:0] load_nfft_value_U0_m_axi_gmem_AWBURST;
wire   [1:0] load_nfft_value_U0_m_axi_gmem_AWLOCK;
wire   [3:0] load_nfft_value_U0_m_axi_gmem_AWCACHE;
wire   [2:0] load_nfft_value_U0_m_axi_gmem_AWPROT;
wire   [3:0] load_nfft_value_U0_m_axi_gmem_AWQOS;
wire   [3:0] load_nfft_value_U0_m_axi_gmem_AWREGION;
wire   [0:0] load_nfft_value_U0_m_axi_gmem_AWUSER;
wire    load_nfft_value_U0_m_axi_gmem_WVALID;
wire   [63:0] load_nfft_value_U0_m_axi_gmem_WDATA;
wire   [7:0] load_nfft_value_U0_m_axi_gmem_WSTRB;
wire    load_nfft_value_U0_m_axi_gmem_WLAST;
wire   [0:0] load_nfft_value_U0_m_axi_gmem_WID;
wire   [0:0] load_nfft_value_U0_m_axi_gmem_WUSER;
wire    load_nfft_value_U0_m_axi_gmem_ARVALID;
wire   [63:0] load_nfft_value_U0_m_axi_gmem_ARADDR;
wire   [0:0] load_nfft_value_U0_m_axi_gmem_ARID;
wire   [31:0] load_nfft_value_U0_m_axi_gmem_ARLEN;
wire   [2:0] load_nfft_value_U0_m_axi_gmem_ARSIZE;
wire   [1:0] load_nfft_value_U0_m_axi_gmem_ARBURST;
wire   [1:0] load_nfft_value_U0_m_axi_gmem_ARLOCK;
wire   [3:0] load_nfft_value_U0_m_axi_gmem_ARCACHE;
wire   [2:0] load_nfft_value_U0_m_axi_gmem_ARPROT;
wire   [3:0] load_nfft_value_U0_m_axi_gmem_ARQOS;
wire   [3:0] load_nfft_value_U0_m_axi_gmem_ARREGION;
wire   [0:0] load_nfft_value_U0_m_axi_gmem_ARUSER;
wire    load_nfft_value_U0_m_axi_gmem_RREADY;
wire    load_nfft_value_U0_m_axi_gmem_BREADY;
wire   [63:0] load_nfft_value_U0_S0_din;
wire    load_nfft_value_U0_S0_write;
wire   [31:0] load_nfft_value_U0_num_c36_din;
wire    load_nfft_value_U0_num_c36_write;
wire    fft_stage_1_U0_ap_start;
wire    fft_stage_1_U0_ap_done;
wire    fft_stage_1_U0_ap_continue;
wire    fft_stage_1_U0_ap_idle;
wire    fft_stage_1_U0_ap_ready;
wire    fft_stage_1_U0_start_out;
wire    fft_stage_1_U0_start_write;
wire    fft_stage_1_U0_S0_read;
wire   [63:0] fft_stage_1_U0_S1_din;
wire    fft_stage_1_U0_S1_write;
wire    fft_stage_1_U0_numFFT_read;
wire   [31:0] fft_stage_1_U0_num_c35_din;
wire    fft_stage_1_U0_num_c35_write;
wire    fft_stage_2_U0_ap_start;
wire    fft_stage_2_U0_ap_done;
wire    fft_stage_2_U0_ap_continue;
wire    fft_stage_2_U0_ap_idle;
wire    fft_stage_2_U0_ap_ready;
wire    fft_stage_2_U0_start_out;
wire    fft_stage_2_U0_start_write;
wire    fft_stage_2_U0_S1_read;
wire   [63:0] fft_stage_2_U0_S2_din;
wire    fft_stage_2_U0_S2_write;
wire    fft_stage_2_U0_numFFT_read;
wire   [31:0] fft_stage_2_U0_num_c34_din;
wire    fft_stage_2_U0_num_c34_write;
wire    fft_stage_3_U0_ap_start;
wire    fft_stage_3_U0_ap_done;
wire    fft_stage_3_U0_ap_continue;
wire    fft_stage_3_U0_ap_idle;
wire    fft_stage_3_U0_ap_ready;
wire    fft_stage_3_U0_start_out;
wire    fft_stage_3_U0_start_write;
wire    fft_stage_3_U0_S2_read;
wire   [63:0] fft_stage_3_U0_S3_din;
wire    fft_stage_3_U0_S3_write;
wire    fft_stage_3_U0_numFFT_read;
wire   [31:0] fft_stage_3_U0_num_c33_din;
wire    fft_stage_3_U0_num_c33_write;
wire    fft_stage_4_U0_ap_start;
wire    fft_stage_4_U0_ap_done;
wire    fft_stage_4_U0_ap_continue;
wire    fft_stage_4_U0_ap_idle;
wire    fft_stage_4_U0_ap_ready;
wire    fft_stage_4_U0_start_out;
wire    fft_stage_4_U0_start_write;
wire    fft_stage_4_U0_S3_read;
wire   [63:0] fft_stage_4_U0_S4_din;
wire    fft_stage_4_U0_S4_write;
wire    fft_stage_4_U0_numFFT_read;
wire   [31:0] fft_stage_4_U0_num_c32_din;
wire    fft_stage_4_U0_num_c32_write;
wire    fft_stage_5_U0_ap_start;
wire    fft_stage_5_U0_ap_done;
wire    fft_stage_5_U0_ap_continue;
wire    fft_stage_5_U0_ap_idle;
wire    fft_stage_5_U0_ap_ready;
wire    fft_stage_5_U0_start_out;
wire    fft_stage_5_U0_start_write;
wire    fft_stage_5_U0_S4_read;
wire   [63:0] fft_stage_5_U0_S5_din;
wire    fft_stage_5_U0_S5_write;
wire    fft_stage_5_U0_numFFT_read;
wire   [31:0] fft_stage_5_U0_num_c31_din;
wire    fft_stage_5_U0_num_c31_write;
wire    fft_stage_6_U0_ap_start;
wire    fft_stage_6_U0_ap_done;
wire    fft_stage_6_U0_ap_continue;
wire    fft_stage_6_U0_ap_idle;
wire    fft_stage_6_U0_ap_ready;
wire    fft_stage_6_U0_start_out;
wire    fft_stage_6_U0_start_write;
wire    fft_stage_6_U0_S5_read;
wire   [63:0] fft_stage_6_U0_S6_din;
wire    fft_stage_6_U0_S6_write;
wire    fft_stage_6_U0_numFFT_read;
wire   [31:0] fft_stage_6_U0_num_c30_din;
wire    fft_stage_6_U0_num_c30_write;
wire    fft_stage_7_U0_ap_start;
wire    fft_stage_7_U0_ap_done;
wire    fft_stage_7_U0_ap_continue;
wire    fft_stage_7_U0_ap_idle;
wire    fft_stage_7_U0_ap_ready;
wire    fft_stage_7_U0_start_out;
wire    fft_stage_7_U0_start_write;
wire    fft_stage_7_U0_S6_read;
wire   [63:0] fft_stage_7_U0_S7_din;
wire    fft_stage_7_U0_S7_write;
wire    fft_stage_7_U0_numFFT_read;
wire   [31:0] fft_stage_7_U0_num_c29_din;
wire    fft_stage_7_U0_num_c29_write;
wire    fft_stage_8_U0_ap_start;
wire    fft_stage_8_U0_ap_done;
wire    fft_stage_8_U0_ap_continue;
wire    fft_stage_8_U0_ap_idle;
wire    fft_stage_8_U0_ap_ready;
wire    fft_stage_8_U0_start_out;
wire    fft_stage_8_U0_start_write;
wire    fft_stage_8_U0_S7_read;
wire   [63:0] fft_stage_8_U0_S8_din;
wire    fft_stage_8_U0_S8_write;
wire    fft_stage_8_U0_numFFT_read;
wire   [31:0] fft_stage_8_U0_num_c28_din;
wire    fft_stage_8_U0_num_c28_write;
wire    fft_stage_9_U0_ap_start;
wire    fft_stage_9_U0_ap_done;
wire    fft_stage_9_U0_ap_continue;
wire    fft_stage_9_U0_ap_idle;
wire    fft_stage_9_U0_ap_ready;
wire    fft_stage_9_U0_start_out;
wire    fft_stage_9_U0_start_write;
wire    fft_stage_9_U0_S8_read;
wire   [63:0] fft_stage_9_U0_S9_din;
wire    fft_stage_9_U0_S9_write;
wire    fft_stage_9_U0_numFFT_read;
wire   [31:0] fft_stage_9_U0_num_c27_din;
wire    fft_stage_9_U0_num_c27_write;
wire    fft_stage_10_U0_ap_start;
wire    fft_stage_10_U0_ap_done;
wire    fft_stage_10_U0_ap_continue;
wire    fft_stage_10_U0_ap_idle;
wire    fft_stage_10_U0_ap_ready;
wire    fft_stage_10_U0_S9_read;
wire   [63:0] fft_stage_10_U0_S10_din;
wire    fft_stage_10_U0_S10_write;
wire    fft_stage_10_U0_numFFT_read;
wire   [31:0] fft_stage_10_U0_num_c_din;
wire    fft_stage_10_U0_num_c_write;
wire    retrieve_nfft_value_U0_ap_start;
wire    retrieve_nfft_value_U0_ap_done;
wire    retrieve_nfft_value_U0_ap_continue;
wire    retrieve_nfft_value_U0_ap_idle;
wire    retrieve_nfft_value_U0_ap_ready;
wire    retrieve_nfft_value_U0_S10_read;
wire    retrieve_nfft_value_U0_m_axi_gmem_AWVALID;
wire   [63:0] retrieve_nfft_value_U0_m_axi_gmem_AWADDR;
wire   [0:0] retrieve_nfft_value_U0_m_axi_gmem_AWID;
wire   [31:0] retrieve_nfft_value_U0_m_axi_gmem_AWLEN;
wire   [2:0] retrieve_nfft_value_U0_m_axi_gmem_AWSIZE;
wire   [1:0] retrieve_nfft_value_U0_m_axi_gmem_AWBURST;
wire   [1:0] retrieve_nfft_value_U0_m_axi_gmem_AWLOCK;
wire   [3:0] retrieve_nfft_value_U0_m_axi_gmem_AWCACHE;
wire   [2:0] retrieve_nfft_value_U0_m_axi_gmem_AWPROT;
wire   [3:0] retrieve_nfft_value_U0_m_axi_gmem_AWQOS;
wire   [3:0] retrieve_nfft_value_U0_m_axi_gmem_AWREGION;
wire   [0:0] retrieve_nfft_value_U0_m_axi_gmem_AWUSER;
wire    retrieve_nfft_value_U0_m_axi_gmem_WVALID;
wire   [63:0] retrieve_nfft_value_U0_m_axi_gmem_WDATA;
wire   [7:0] retrieve_nfft_value_U0_m_axi_gmem_WSTRB;
wire    retrieve_nfft_value_U0_m_axi_gmem_WLAST;
wire   [0:0] retrieve_nfft_value_U0_m_axi_gmem_WID;
wire   [0:0] retrieve_nfft_value_U0_m_axi_gmem_WUSER;
wire    retrieve_nfft_value_U0_m_axi_gmem_ARVALID;
wire   [63:0] retrieve_nfft_value_U0_m_axi_gmem_ARADDR;
wire   [0:0] retrieve_nfft_value_U0_m_axi_gmem_ARID;
wire   [31:0] retrieve_nfft_value_U0_m_axi_gmem_ARLEN;
wire   [2:0] retrieve_nfft_value_U0_m_axi_gmem_ARSIZE;
wire   [1:0] retrieve_nfft_value_U0_m_axi_gmem_ARBURST;
wire   [1:0] retrieve_nfft_value_U0_m_axi_gmem_ARLOCK;
wire   [3:0] retrieve_nfft_value_U0_m_axi_gmem_ARCACHE;
wire   [2:0] retrieve_nfft_value_U0_m_axi_gmem_ARPROT;
wire   [3:0] retrieve_nfft_value_U0_m_axi_gmem_ARQOS;
wire   [3:0] retrieve_nfft_value_U0_m_axi_gmem_ARREGION;
wire   [0:0] retrieve_nfft_value_U0_m_axi_gmem_ARUSER;
wire    retrieve_nfft_value_U0_m_axi_gmem_RREADY;
wire    retrieve_nfft_value_U0_m_axi_gmem_BREADY;
wire    retrieve_nfft_value_U0_out_r_read;
wire    retrieve_nfft_value_U0_numFFT_read;
wire    out_c_full_n;
wire   [63:0] out_c_dout;
wire   [4:0] out_c_num_data_valid;
wire   [4:0] out_c_fifo_cap;
wire    out_c_empty_n;
wire    S0_full_n;
wire   [63:0] S0_dout;
wire   [10:0] S0_num_data_valid;
wire   [10:0] S0_fifo_cap;
wire    S0_empty_n;
wire    num_c36_full_n;
wire   [31:0] num_c36_dout;
wire   [1:0] num_c36_num_data_valid;
wire   [1:0] num_c36_fifo_cap;
wire    num_c36_empty_n;
wire    S1_full_n;
wire   [63:0] S1_dout;
wire   [10:0] S1_num_data_valid;
wire   [10:0] S1_fifo_cap;
wire    S1_empty_n;
wire    num_c35_full_n;
wire   [31:0] num_c35_dout;
wire   [1:0] num_c35_num_data_valid;
wire   [1:0] num_c35_fifo_cap;
wire    num_c35_empty_n;
wire    S2_full_n;
wire   [63:0] S2_dout;
wire   [10:0] S2_num_data_valid;
wire   [10:0] S2_fifo_cap;
wire    S2_empty_n;
wire    num_c34_full_n;
wire   [31:0] num_c34_dout;
wire   [1:0] num_c34_num_data_valid;
wire   [1:0] num_c34_fifo_cap;
wire    num_c34_empty_n;
wire    S3_full_n;
wire   [63:0] S3_dout;
wire   [10:0] S3_num_data_valid;
wire   [10:0] S3_fifo_cap;
wire    S3_empty_n;
wire    num_c33_full_n;
wire   [31:0] num_c33_dout;
wire   [1:0] num_c33_num_data_valid;
wire   [1:0] num_c33_fifo_cap;
wire    num_c33_empty_n;
wire    S4_full_n;
wire   [63:0] S4_dout;
wire   [10:0] S4_num_data_valid;
wire   [10:0] S4_fifo_cap;
wire    S4_empty_n;
wire    num_c32_full_n;
wire   [31:0] num_c32_dout;
wire   [1:0] num_c32_num_data_valid;
wire   [1:0] num_c32_fifo_cap;
wire    num_c32_empty_n;
wire    S5_full_n;
wire   [63:0] S5_dout;
wire   [10:0] S5_num_data_valid;
wire   [10:0] S5_fifo_cap;
wire    S5_empty_n;
wire    num_c31_full_n;
wire   [31:0] num_c31_dout;
wire   [1:0] num_c31_num_data_valid;
wire   [1:0] num_c31_fifo_cap;
wire    num_c31_empty_n;
wire    S6_full_n;
wire   [63:0] S6_dout;
wire   [10:0] S6_num_data_valid;
wire   [10:0] S6_fifo_cap;
wire    S6_empty_n;
wire    num_c30_full_n;
wire   [31:0] num_c30_dout;
wire   [1:0] num_c30_num_data_valid;
wire   [1:0] num_c30_fifo_cap;
wire    num_c30_empty_n;
wire    S7_full_n;
wire   [63:0] S7_dout;
wire   [10:0] S7_num_data_valid;
wire   [10:0] S7_fifo_cap;
wire    S7_empty_n;
wire    num_c29_full_n;
wire   [31:0] num_c29_dout;
wire   [1:0] num_c29_num_data_valid;
wire   [1:0] num_c29_fifo_cap;
wire    num_c29_empty_n;
wire    S8_full_n;
wire   [63:0] S8_dout;
wire   [10:0] S8_num_data_valid;
wire   [10:0] S8_fifo_cap;
wire    S8_empty_n;
wire    num_c28_full_n;
wire   [31:0] num_c28_dout;
wire   [1:0] num_c28_num_data_valid;
wire   [1:0] num_c28_fifo_cap;
wire    num_c28_empty_n;
wire    S9_full_n;
wire   [63:0] S9_dout;
wire   [10:0] S9_num_data_valid;
wire   [10:0] S9_fifo_cap;
wire    S9_empty_n;
wire    num_c27_full_n;
wire   [31:0] num_c27_dout;
wire   [1:0] num_c27_num_data_valid;
wire   [1:0] num_c27_fifo_cap;
wire    num_c27_empty_n;
wire    S10_full_n;
wire   [63:0] S10_dout;
wire   [10:0] S10_num_data_valid;
wire   [10:0] S10_fifo_cap;
wire    S10_empty_n;
wire    num_c_full_n;
wire   [31:0] num_c_dout;
wire   [1:0] num_c_num_data_valid;
wire   [1:0] num_c_fifo_cap;
wire    num_c_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_load_nfft_value_U0_ap_ready;
wire    ap_sync_load_nfft_value_U0_ap_ready;
wire   [0:0] start_for_retrieve_nfft_value_U0_din;
wire    start_for_retrieve_nfft_value_U0_full_n;
wire   [0:0] start_for_retrieve_nfft_value_U0_dout;
wire    start_for_retrieve_nfft_value_U0_empty_n;
wire   [0:0] start_for_fft_stage_1_U0_din;
wire    start_for_fft_stage_1_U0_full_n;
wire   [0:0] start_for_fft_stage_1_U0_dout;
wire    start_for_fft_stage_1_U0_empty_n;
wire   [0:0] start_for_fft_stage_2_U0_din;
wire    start_for_fft_stage_2_U0_full_n;
wire   [0:0] start_for_fft_stage_2_U0_dout;
wire    start_for_fft_stage_2_U0_empty_n;
wire   [0:0] start_for_fft_stage_3_U0_din;
wire    start_for_fft_stage_3_U0_full_n;
wire   [0:0] start_for_fft_stage_3_U0_dout;
wire    start_for_fft_stage_3_U0_empty_n;
wire   [0:0] start_for_fft_stage_4_U0_din;
wire    start_for_fft_stage_4_U0_full_n;
wire   [0:0] start_for_fft_stage_4_U0_dout;
wire    start_for_fft_stage_4_U0_empty_n;
wire   [0:0] start_for_fft_stage_5_U0_din;
wire    start_for_fft_stage_5_U0_full_n;
wire   [0:0] start_for_fft_stage_5_U0_dout;
wire    start_for_fft_stage_5_U0_empty_n;
wire   [0:0] start_for_fft_stage_6_U0_din;
wire    start_for_fft_stage_6_U0_full_n;
wire   [0:0] start_for_fft_stage_6_U0_dout;
wire    start_for_fft_stage_6_U0_empty_n;
wire   [0:0] start_for_fft_stage_7_U0_din;
wire    start_for_fft_stage_7_U0_full_n;
wire   [0:0] start_for_fft_stage_7_U0_dout;
wire    start_for_fft_stage_7_U0_empty_n;
wire   [0:0] start_for_fft_stage_8_U0_din;
wire    start_for_fft_stage_8_U0_full_n;
wire   [0:0] start_for_fft_stage_8_U0_dout;
wire    start_for_fft_stage_8_U0_empty_n;
wire   [0:0] start_for_fft_stage_9_U0_din;
wire    start_for_fft_stage_9_U0_full_n;
wire   [0:0] start_for_fft_stage_9_U0_dout;
wire    start_for_fft_stage_9_U0_empty_n;
wire   [0:0] start_for_fft_stage_10_U0_din;
wire    start_for_fft_stage_10_U0_full_n;
wire   [0:0] start_for_fft_stage_10_U0_dout;
wire    start_for_fft_stage_10_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_load_nfft_value_U0_ap_ready = 1'b0;
end

fft_HW_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(entry_proc_U0_ap_start),
    .start_full_n(start_for_retrieve_nfft_value_U0_full_n),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .start_out(entry_proc_U0_start_out),
    .start_write(entry_proc_U0_start_write),
    .out_r(out_r),
    .out_c_din(entry_proc_U0_out_c_din),
    .out_c_num_data_valid(out_c_num_data_valid),
    .out_c_fifo_cap(out_c_fifo_cap),
    .out_c_full_n(out_c_full_n),
    .out_c_write(entry_proc_U0_out_c_write)
);

fft_HW_load_nfft_value load_nfft_value_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(load_nfft_value_U0_ap_start),
    .start_full_n(start_for_fft_stage_1_U0_full_n),
    .ap_done(load_nfft_value_U0_ap_done),
    .ap_continue(load_nfft_value_U0_ap_continue),
    .ap_idle(load_nfft_value_U0_ap_idle),
    .ap_ready(load_nfft_value_U0_ap_ready),
    .start_out(load_nfft_value_U0_start_out),
    .start_write(load_nfft_value_U0_start_write),
    .m_axi_gmem_AWVALID(load_nfft_value_U0_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(load_nfft_value_U0_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(load_nfft_value_U0_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(load_nfft_value_U0_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(load_nfft_value_U0_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(load_nfft_value_U0_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(load_nfft_value_U0_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(load_nfft_value_U0_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(load_nfft_value_U0_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(load_nfft_value_U0_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(load_nfft_value_U0_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(load_nfft_value_U0_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(load_nfft_value_U0_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(load_nfft_value_U0_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(load_nfft_value_U0_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(load_nfft_value_U0_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(load_nfft_value_U0_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(load_nfft_value_U0_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(load_nfft_value_U0_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(m_axi_gmem_ARREADY),
    .m_axi_gmem_ARADDR(load_nfft_value_U0_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(load_nfft_value_U0_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(load_nfft_value_U0_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(load_nfft_value_U0_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(load_nfft_value_U0_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(load_nfft_value_U0_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(load_nfft_value_U0_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(load_nfft_value_U0_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(load_nfft_value_U0_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(load_nfft_value_U0_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(load_nfft_value_U0_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(m_axi_gmem_RVALID),
    .m_axi_gmem_RREADY(load_nfft_value_U0_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(m_axi_gmem_RDATA),
    .m_axi_gmem_RLAST(m_axi_gmem_RLAST),
    .m_axi_gmem_RID(m_axi_gmem_RID),
    .m_axi_gmem_RFIFONUM(m_axi_gmem_RFIFONUM),
    .m_axi_gmem_RUSER(m_axi_gmem_RUSER),
    .m_axi_gmem_RRESP(m_axi_gmem_RRESP),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(load_nfft_value_U0_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .in_r(in_r),
    .S0_din(load_nfft_value_U0_S0_din),
    .S0_num_data_valid(S0_num_data_valid),
    .S0_fifo_cap(S0_fifo_cap),
    .S0_full_n(S0_full_n),
    .S0_write(load_nfft_value_U0_S0_write),
    .numFFT(num),
    .num_c36_din(load_nfft_value_U0_num_c36_din),
    .num_c36_num_data_valid(num_c36_num_data_valid),
    .num_c36_fifo_cap(num_c36_fifo_cap),
    .num_c36_full_n(num_c36_full_n),
    .num_c36_write(load_nfft_value_U0_num_c36_write)
);

fft_HW_fft_stage_1 fft_stage_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fft_stage_1_U0_ap_start),
    .start_full_n(start_for_fft_stage_2_U0_full_n),
    .ap_done(fft_stage_1_U0_ap_done),
    .ap_continue(fft_stage_1_U0_ap_continue),
    .ap_idle(fft_stage_1_U0_ap_idle),
    .ap_ready(fft_stage_1_U0_ap_ready),
    .start_out(fft_stage_1_U0_start_out),
    .start_write(fft_stage_1_U0_start_write),
    .S0_dout(S0_dout),
    .S0_num_data_valid(S0_num_data_valid),
    .S0_fifo_cap(S0_fifo_cap),
    .S0_empty_n(S0_empty_n),
    .S0_read(fft_stage_1_U0_S0_read),
    .S1_din(fft_stage_1_U0_S1_din),
    .S1_num_data_valid(S1_num_data_valid),
    .S1_fifo_cap(S1_fifo_cap),
    .S1_full_n(S1_full_n),
    .S1_write(fft_stage_1_U0_S1_write),
    .numFFT_dout(num_c36_dout),
    .numFFT_num_data_valid(num_c36_num_data_valid),
    .numFFT_fifo_cap(num_c36_fifo_cap),
    .numFFT_empty_n(num_c36_empty_n),
    .numFFT_read(fft_stage_1_U0_numFFT_read),
    .num_c35_din(fft_stage_1_U0_num_c35_din),
    .num_c35_num_data_valid(num_c35_num_data_valid),
    .num_c35_fifo_cap(num_c35_fifo_cap),
    .num_c35_full_n(num_c35_full_n),
    .num_c35_write(fft_stage_1_U0_num_c35_write)
);

fft_HW_fft_stage_2 fft_stage_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fft_stage_2_U0_ap_start),
    .start_full_n(start_for_fft_stage_3_U0_full_n),
    .ap_done(fft_stage_2_U0_ap_done),
    .ap_continue(fft_stage_2_U0_ap_continue),
    .ap_idle(fft_stage_2_U0_ap_idle),
    .ap_ready(fft_stage_2_U0_ap_ready),
    .start_out(fft_stage_2_U0_start_out),
    .start_write(fft_stage_2_U0_start_write),
    .S1_dout(S1_dout),
    .S1_num_data_valid(S1_num_data_valid),
    .S1_fifo_cap(S1_fifo_cap),
    .S1_empty_n(S1_empty_n),
    .S1_read(fft_stage_2_U0_S1_read),
    .S2_din(fft_stage_2_U0_S2_din),
    .S2_num_data_valid(S2_num_data_valid),
    .S2_fifo_cap(S2_fifo_cap),
    .S2_full_n(S2_full_n),
    .S2_write(fft_stage_2_U0_S2_write),
    .numFFT_dout(num_c35_dout),
    .numFFT_num_data_valid(num_c35_num_data_valid),
    .numFFT_fifo_cap(num_c35_fifo_cap),
    .numFFT_empty_n(num_c35_empty_n),
    .numFFT_read(fft_stage_2_U0_numFFT_read),
    .num_c34_din(fft_stage_2_U0_num_c34_din),
    .num_c34_num_data_valid(num_c34_num_data_valid),
    .num_c34_fifo_cap(num_c34_fifo_cap),
    .num_c34_full_n(num_c34_full_n),
    .num_c34_write(fft_stage_2_U0_num_c34_write)
);

fft_HW_fft_stage_3 fft_stage_3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fft_stage_3_U0_ap_start),
    .start_full_n(start_for_fft_stage_4_U0_full_n),
    .ap_done(fft_stage_3_U0_ap_done),
    .ap_continue(fft_stage_3_U0_ap_continue),
    .ap_idle(fft_stage_3_U0_ap_idle),
    .ap_ready(fft_stage_3_U0_ap_ready),
    .start_out(fft_stage_3_U0_start_out),
    .start_write(fft_stage_3_U0_start_write),
    .S2_dout(S2_dout),
    .S2_num_data_valid(S2_num_data_valid),
    .S2_fifo_cap(S2_fifo_cap),
    .S2_empty_n(S2_empty_n),
    .S2_read(fft_stage_3_U0_S2_read),
    .S3_din(fft_stage_3_U0_S3_din),
    .S3_num_data_valid(S3_num_data_valid),
    .S3_fifo_cap(S3_fifo_cap),
    .S3_full_n(S3_full_n),
    .S3_write(fft_stage_3_U0_S3_write),
    .numFFT_dout(num_c34_dout),
    .numFFT_num_data_valid(num_c34_num_data_valid),
    .numFFT_fifo_cap(num_c34_fifo_cap),
    .numFFT_empty_n(num_c34_empty_n),
    .numFFT_read(fft_stage_3_U0_numFFT_read),
    .num_c33_din(fft_stage_3_U0_num_c33_din),
    .num_c33_num_data_valid(num_c33_num_data_valid),
    .num_c33_fifo_cap(num_c33_fifo_cap),
    .num_c33_full_n(num_c33_full_n),
    .num_c33_write(fft_stage_3_U0_num_c33_write)
);

fft_HW_fft_stage_4 fft_stage_4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fft_stage_4_U0_ap_start),
    .start_full_n(start_for_fft_stage_5_U0_full_n),
    .ap_done(fft_stage_4_U0_ap_done),
    .ap_continue(fft_stage_4_U0_ap_continue),
    .ap_idle(fft_stage_4_U0_ap_idle),
    .ap_ready(fft_stage_4_U0_ap_ready),
    .start_out(fft_stage_4_U0_start_out),
    .start_write(fft_stage_4_U0_start_write),
    .S3_dout(S3_dout),
    .S3_num_data_valid(S3_num_data_valid),
    .S3_fifo_cap(S3_fifo_cap),
    .S3_empty_n(S3_empty_n),
    .S3_read(fft_stage_4_U0_S3_read),
    .S4_din(fft_stage_4_U0_S4_din),
    .S4_num_data_valid(S4_num_data_valid),
    .S4_fifo_cap(S4_fifo_cap),
    .S4_full_n(S4_full_n),
    .S4_write(fft_stage_4_U0_S4_write),
    .numFFT_dout(num_c33_dout),
    .numFFT_num_data_valid(num_c33_num_data_valid),
    .numFFT_fifo_cap(num_c33_fifo_cap),
    .numFFT_empty_n(num_c33_empty_n),
    .numFFT_read(fft_stage_4_U0_numFFT_read),
    .num_c32_din(fft_stage_4_U0_num_c32_din),
    .num_c32_num_data_valid(num_c32_num_data_valid),
    .num_c32_fifo_cap(num_c32_fifo_cap),
    .num_c32_full_n(num_c32_full_n),
    .num_c32_write(fft_stage_4_U0_num_c32_write)
);

fft_HW_fft_stage_5 fft_stage_5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fft_stage_5_U0_ap_start),
    .start_full_n(start_for_fft_stage_6_U0_full_n),
    .ap_done(fft_stage_5_U0_ap_done),
    .ap_continue(fft_stage_5_U0_ap_continue),
    .ap_idle(fft_stage_5_U0_ap_idle),
    .ap_ready(fft_stage_5_U0_ap_ready),
    .start_out(fft_stage_5_U0_start_out),
    .start_write(fft_stage_5_U0_start_write),
    .S4_dout(S4_dout),
    .S4_num_data_valid(S4_num_data_valid),
    .S4_fifo_cap(S4_fifo_cap),
    .S4_empty_n(S4_empty_n),
    .S4_read(fft_stage_5_U0_S4_read),
    .S5_din(fft_stage_5_U0_S5_din),
    .S5_num_data_valid(S5_num_data_valid),
    .S5_fifo_cap(S5_fifo_cap),
    .S5_full_n(S5_full_n),
    .S5_write(fft_stage_5_U0_S5_write),
    .numFFT_dout(num_c32_dout),
    .numFFT_num_data_valid(num_c32_num_data_valid),
    .numFFT_fifo_cap(num_c32_fifo_cap),
    .numFFT_empty_n(num_c32_empty_n),
    .numFFT_read(fft_stage_5_U0_numFFT_read),
    .num_c31_din(fft_stage_5_U0_num_c31_din),
    .num_c31_num_data_valid(num_c31_num_data_valid),
    .num_c31_fifo_cap(num_c31_fifo_cap),
    .num_c31_full_n(num_c31_full_n),
    .num_c31_write(fft_stage_5_U0_num_c31_write)
);

fft_HW_fft_stage_6 fft_stage_6_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fft_stage_6_U0_ap_start),
    .start_full_n(start_for_fft_stage_7_U0_full_n),
    .ap_done(fft_stage_6_U0_ap_done),
    .ap_continue(fft_stage_6_U0_ap_continue),
    .ap_idle(fft_stage_6_U0_ap_idle),
    .ap_ready(fft_stage_6_U0_ap_ready),
    .start_out(fft_stage_6_U0_start_out),
    .start_write(fft_stage_6_U0_start_write),
    .S5_dout(S5_dout),
    .S5_num_data_valid(S5_num_data_valid),
    .S5_fifo_cap(S5_fifo_cap),
    .S5_empty_n(S5_empty_n),
    .S5_read(fft_stage_6_U0_S5_read),
    .S6_din(fft_stage_6_U0_S6_din),
    .S6_num_data_valid(S6_num_data_valid),
    .S6_fifo_cap(S6_fifo_cap),
    .S6_full_n(S6_full_n),
    .S6_write(fft_stage_6_U0_S6_write),
    .numFFT_dout(num_c31_dout),
    .numFFT_num_data_valid(num_c31_num_data_valid),
    .numFFT_fifo_cap(num_c31_fifo_cap),
    .numFFT_empty_n(num_c31_empty_n),
    .numFFT_read(fft_stage_6_U0_numFFT_read),
    .num_c30_din(fft_stage_6_U0_num_c30_din),
    .num_c30_num_data_valid(num_c30_num_data_valid),
    .num_c30_fifo_cap(num_c30_fifo_cap),
    .num_c30_full_n(num_c30_full_n),
    .num_c30_write(fft_stage_6_U0_num_c30_write)
);

fft_HW_fft_stage_7 fft_stage_7_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fft_stage_7_U0_ap_start),
    .start_full_n(start_for_fft_stage_8_U0_full_n),
    .ap_done(fft_stage_7_U0_ap_done),
    .ap_continue(fft_stage_7_U0_ap_continue),
    .ap_idle(fft_stage_7_U0_ap_idle),
    .ap_ready(fft_stage_7_U0_ap_ready),
    .start_out(fft_stage_7_U0_start_out),
    .start_write(fft_stage_7_U0_start_write),
    .S6_dout(S6_dout),
    .S6_num_data_valid(S6_num_data_valid),
    .S6_fifo_cap(S6_fifo_cap),
    .S6_empty_n(S6_empty_n),
    .S6_read(fft_stage_7_U0_S6_read),
    .S7_din(fft_stage_7_U0_S7_din),
    .S7_num_data_valid(S7_num_data_valid),
    .S7_fifo_cap(S7_fifo_cap),
    .S7_full_n(S7_full_n),
    .S7_write(fft_stage_7_U0_S7_write),
    .numFFT_dout(num_c30_dout),
    .numFFT_num_data_valid(num_c30_num_data_valid),
    .numFFT_fifo_cap(num_c30_fifo_cap),
    .numFFT_empty_n(num_c30_empty_n),
    .numFFT_read(fft_stage_7_U0_numFFT_read),
    .num_c29_din(fft_stage_7_U0_num_c29_din),
    .num_c29_num_data_valid(num_c29_num_data_valid),
    .num_c29_fifo_cap(num_c29_fifo_cap),
    .num_c29_full_n(num_c29_full_n),
    .num_c29_write(fft_stage_7_U0_num_c29_write)
);

fft_HW_fft_stage_8 fft_stage_8_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fft_stage_8_U0_ap_start),
    .start_full_n(start_for_fft_stage_9_U0_full_n),
    .ap_done(fft_stage_8_U0_ap_done),
    .ap_continue(fft_stage_8_U0_ap_continue),
    .ap_idle(fft_stage_8_U0_ap_idle),
    .ap_ready(fft_stage_8_U0_ap_ready),
    .start_out(fft_stage_8_U0_start_out),
    .start_write(fft_stage_8_U0_start_write),
    .S7_dout(S7_dout),
    .S7_num_data_valid(S7_num_data_valid),
    .S7_fifo_cap(S7_fifo_cap),
    .S7_empty_n(S7_empty_n),
    .S7_read(fft_stage_8_U0_S7_read),
    .S8_din(fft_stage_8_U0_S8_din),
    .S8_num_data_valid(S8_num_data_valid),
    .S8_fifo_cap(S8_fifo_cap),
    .S8_full_n(S8_full_n),
    .S8_write(fft_stage_8_U0_S8_write),
    .numFFT_dout(num_c29_dout),
    .numFFT_num_data_valid(num_c29_num_data_valid),
    .numFFT_fifo_cap(num_c29_fifo_cap),
    .numFFT_empty_n(num_c29_empty_n),
    .numFFT_read(fft_stage_8_U0_numFFT_read),
    .num_c28_din(fft_stage_8_U0_num_c28_din),
    .num_c28_num_data_valid(num_c28_num_data_valid),
    .num_c28_fifo_cap(num_c28_fifo_cap),
    .num_c28_full_n(num_c28_full_n),
    .num_c28_write(fft_stage_8_U0_num_c28_write)
);

fft_HW_fft_stage_9 fft_stage_9_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fft_stage_9_U0_ap_start),
    .start_full_n(start_for_fft_stage_10_U0_full_n),
    .ap_done(fft_stage_9_U0_ap_done),
    .ap_continue(fft_stage_9_U0_ap_continue),
    .ap_idle(fft_stage_9_U0_ap_idle),
    .ap_ready(fft_stage_9_U0_ap_ready),
    .start_out(fft_stage_9_U0_start_out),
    .start_write(fft_stage_9_U0_start_write),
    .S8_dout(S8_dout),
    .S8_num_data_valid(S8_num_data_valid),
    .S8_fifo_cap(S8_fifo_cap),
    .S8_empty_n(S8_empty_n),
    .S8_read(fft_stage_9_U0_S8_read),
    .S9_din(fft_stage_9_U0_S9_din),
    .S9_num_data_valid(S9_num_data_valid),
    .S9_fifo_cap(S9_fifo_cap),
    .S9_full_n(S9_full_n),
    .S9_write(fft_stage_9_U0_S9_write),
    .numFFT_dout(num_c28_dout),
    .numFFT_num_data_valid(num_c28_num_data_valid),
    .numFFT_fifo_cap(num_c28_fifo_cap),
    .numFFT_empty_n(num_c28_empty_n),
    .numFFT_read(fft_stage_9_U0_numFFT_read),
    .num_c27_din(fft_stage_9_U0_num_c27_din),
    .num_c27_num_data_valid(num_c27_num_data_valid),
    .num_c27_fifo_cap(num_c27_fifo_cap),
    .num_c27_full_n(num_c27_full_n),
    .num_c27_write(fft_stage_9_U0_num_c27_write)
);

fft_HW_fft_stage_10 fft_stage_10_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fft_stage_10_U0_ap_start),
    .ap_done(fft_stage_10_U0_ap_done),
    .ap_continue(fft_stage_10_U0_ap_continue),
    .ap_idle(fft_stage_10_U0_ap_idle),
    .ap_ready(fft_stage_10_U0_ap_ready),
    .S9_dout(S9_dout),
    .S9_num_data_valid(S9_num_data_valid),
    .S9_fifo_cap(S9_fifo_cap),
    .S9_empty_n(S9_empty_n),
    .S9_read(fft_stage_10_U0_S9_read),
    .S10_din(fft_stage_10_U0_S10_din),
    .S10_num_data_valid(S10_num_data_valid),
    .S10_fifo_cap(S10_fifo_cap),
    .S10_full_n(S10_full_n),
    .S10_write(fft_stage_10_U0_S10_write),
    .numFFT_dout(num_c27_dout),
    .numFFT_num_data_valid(num_c27_num_data_valid),
    .numFFT_fifo_cap(num_c27_fifo_cap),
    .numFFT_empty_n(num_c27_empty_n),
    .numFFT_read(fft_stage_10_U0_numFFT_read),
    .num_c_din(fft_stage_10_U0_num_c_din),
    .num_c_num_data_valid(num_c_num_data_valid),
    .num_c_fifo_cap(num_c_fifo_cap),
    .num_c_full_n(num_c_full_n),
    .num_c_write(fft_stage_10_U0_num_c_write)
);

fft_HW_retrieve_nfft_value retrieve_nfft_value_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(retrieve_nfft_value_U0_ap_start),
    .ap_done(retrieve_nfft_value_U0_ap_done),
    .ap_continue(retrieve_nfft_value_U0_ap_continue),
    .ap_idle(retrieve_nfft_value_U0_ap_idle),
    .ap_ready(retrieve_nfft_value_U0_ap_ready),
    .S10_dout(S10_dout),
    .S10_num_data_valid(S10_num_data_valid),
    .S10_fifo_cap(S10_fifo_cap),
    .S10_empty_n(S10_empty_n),
    .S10_read(retrieve_nfft_value_U0_S10_read),
    .m_axi_gmem_AWVALID(retrieve_nfft_value_U0_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(m_axi_gmem_AWREADY),
    .m_axi_gmem_AWADDR(retrieve_nfft_value_U0_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(retrieve_nfft_value_U0_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(retrieve_nfft_value_U0_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(retrieve_nfft_value_U0_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(retrieve_nfft_value_U0_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(retrieve_nfft_value_U0_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(retrieve_nfft_value_U0_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(retrieve_nfft_value_U0_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(retrieve_nfft_value_U0_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(retrieve_nfft_value_U0_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(retrieve_nfft_value_U0_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(retrieve_nfft_value_U0_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(m_axi_gmem_WREADY),
    .m_axi_gmem_WDATA(retrieve_nfft_value_U0_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(retrieve_nfft_value_U0_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(retrieve_nfft_value_U0_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(retrieve_nfft_value_U0_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(retrieve_nfft_value_U0_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(retrieve_nfft_value_U0_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(1'b0),
    .m_axi_gmem_ARADDR(retrieve_nfft_value_U0_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(retrieve_nfft_value_U0_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(retrieve_nfft_value_U0_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(retrieve_nfft_value_U0_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(retrieve_nfft_value_U0_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(retrieve_nfft_value_U0_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(retrieve_nfft_value_U0_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(retrieve_nfft_value_U0_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(retrieve_nfft_value_U0_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(retrieve_nfft_value_U0_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(retrieve_nfft_value_U0_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(1'b0),
    .m_axi_gmem_RREADY(retrieve_nfft_value_U0_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(64'd0),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(9'd0),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(m_axi_gmem_BVALID),
    .m_axi_gmem_BREADY(retrieve_nfft_value_U0_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(m_axi_gmem_BRESP),
    .m_axi_gmem_BID(m_axi_gmem_BID),
    .m_axi_gmem_BUSER(m_axi_gmem_BUSER),
    .out_r_dout(out_c_dout),
    .out_r_num_data_valid(out_c_num_data_valid),
    .out_r_fifo_cap(out_c_fifo_cap),
    .out_r_empty_n(out_c_empty_n),
    .out_r_read(retrieve_nfft_value_U0_out_r_read),
    .numFFT_dout(num_c_dout),
    .numFFT_num_data_valid(num_c_num_data_valid),
    .numFFT_fifo_cap(num_c_fifo_cap),
    .numFFT_empty_n(num_c_empty_n),
    .numFFT_read(retrieve_nfft_value_U0_numFFT_read)
);

fft_HW_fifo_w64_d13_S out_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_out_c_din),
    .if_full_n(out_c_full_n),
    .if_write(entry_proc_U0_out_c_write),
    .if_dout(out_c_dout),
    .if_num_data_valid(out_c_num_data_valid),
    .if_fifo_cap(out_c_fifo_cap),
    .if_empty_n(out_c_empty_n),
    .if_read(retrieve_nfft_value_U0_out_r_read)
);

fft_HW_fifo_w64_d1024_A S0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_nfft_value_U0_S0_din),
    .if_full_n(S0_full_n),
    .if_write(load_nfft_value_U0_S0_write),
    .if_dout(S0_dout),
    .if_num_data_valid(S0_num_data_valid),
    .if_fifo_cap(S0_fifo_cap),
    .if_empty_n(S0_empty_n),
    .if_read(fft_stage_1_U0_S0_read)
);

fft_HW_fifo_w32_d2_S num_c36_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_nfft_value_U0_num_c36_din),
    .if_full_n(num_c36_full_n),
    .if_write(load_nfft_value_U0_num_c36_write),
    .if_dout(num_c36_dout),
    .if_num_data_valid(num_c36_num_data_valid),
    .if_fifo_cap(num_c36_fifo_cap),
    .if_empty_n(num_c36_empty_n),
    .if_read(fft_stage_1_U0_numFFT_read)
);

fft_HW_fifo_w64_d1024_A S1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_stage_1_U0_S1_din),
    .if_full_n(S1_full_n),
    .if_write(fft_stage_1_U0_S1_write),
    .if_dout(S1_dout),
    .if_num_data_valid(S1_num_data_valid),
    .if_fifo_cap(S1_fifo_cap),
    .if_empty_n(S1_empty_n),
    .if_read(fft_stage_2_U0_S1_read)
);

fft_HW_fifo_w32_d2_S num_c35_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_stage_1_U0_num_c35_din),
    .if_full_n(num_c35_full_n),
    .if_write(fft_stage_1_U0_num_c35_write),
    .if_dout(num_c35_dout),
    .if_num_data_valid(num_c35_num_data_valid),
    .if_fifo_cap(num_c35_fifo_cap),
    .if_empty_n(num_c35_empty_n),
    .if_read(fft_stage_2_U0_numFFT_read)
);

fft_HW_fifo_w64_d1024_A S2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_stage_2_U0_S2_din),
    .if_full_n(S2_full_n),
    .if_write(fft_stage_2_U0_S2_write),
    .if_dout(S2_dout),
    .if_num_data_valid(S2_num_data_valid),
    .if_fifo_cap(S2_fifo_cap),
    .if_empty_n(S2_empty_n),
    .if_read(fft_stage_3_U0_S2_read)
);

fft_HW_fifo_w32_d2_S num_c34_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_stage_2_U0_num_c34_din),
    .if_full_n(num_c34_full_n),
    .if_write(fft_stage_2_U0_num_c34_write),
    .if_dout(num_c34_dout),
    .if_num_data_valid(num_c34_num_data_valid),
    .if_fifo_cap(num_c34_fifo_cap),
    .if_empty_n(num_c34_empty_n),
    .if_read(fft_stage_3_U0_numFFT_read)
);

fft_HW_fifo_w64_d1024_A S3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_stage_3_U0_S3_din),
    .if_full_n(S3_full_n),
    .if_write(fft_stage_3_U0_S3_write),
    .if_dout(S3_dout),
    .if_num_data_valid(S3_num_data_valid),
    .if_fifo_cap(S3_fifo_cap),
    .if_empty_n(S3_empty_n),
    .if_read(fft_stage_4_U0_S3_read)
);

fft_HW_fifo_w32_d2_S num_c33_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_stage_3_U0_num_c33_din),
    .if_full_n(num_c33_full_n),
    .if_write(fft_stage_3_U0_num_c33_write),
    .if_dout(num_c33_dout),
    .if_num_data_valid(num_c33_num_data_valid),
    .if_fifo_cap(num_c33_fifo_cap),
    .if_empty_n(num_c33_empty_n),
    .if_read(fft_stage_4_U0_numFFT_read)
);

fft_HW_fifo_w64_d1024_A S4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_stage_4_U0_S4_din),
    .if_full_n(S4_full_n),
    .if_write(fft_stage_4_U0_S4_write),
    .if_dout(S4_dout),
    .if_num_data_valid(S4_num_data_valid),
    .if_fifo_cap(S4_fifo_cap),
    .if_empty_n(S4_empty_n),
    .if_read(fft_stage_5_U0_S4_read)
);

fft_HW_fifo_w32_d2_S num_c32_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_stage_4_U0_num_c32_din),
    .if_full_n(num_c32_full_n),
    .if_write(fft_stage_4_U0_num_c32_write),
    .if_dout(num_c32_dout),
    .if_num_data_valid(num_c32_num_data_valid),
    .if_fifo_cap(num_c32_fifo_cap),
    .if_empty_n(num_c32_empty_n),
    .if_read(fft_stage_5_U0_numFFT_read)
);

fft_HW_fifo_w64_d1024_A S5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_stage_5_U0_S5_din),
    .if_full_n(S5_full_n),
    .if_write(fft_stage_5_U0_S5_write),
    .if_dout(S5_dout),
    .if_num_data_valid(S5_num_data_valid),
    .if_fifo_cap(S5_fifo_cap),
    .if_empty_n(S5_empty_n),
    .if_read(fft_stage_6_U0_S5_read)
);

fft_HW_fifo_w32_d2_S num_c31_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_stage_5_U0_num_c31_din),
    .if_full_n(num_c31_full_n),
    .if_write(fft_stage_5_U0_num_c31_write),
    .if_dout(num_c31_dout),
    .if_num_data_valid(num_c31_num_data_valid),
    .if_fifo_cap(num_c31_fifo_cap),
    .if_empty_n(num_c31_empty_n),
    .if_read(fft_stage_6_U0_numFFT_read)
);

fft_HW_fifo_w64_d1024_A S6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_stage_6_U0_S6_din),
    .if_full_n(S6_full_n),
    .if_write(fft_stage_6_U0_S6_write),
    .if_dout(S6_dout),
    .if_num_data_valid(S6_num_data_valid),
    .if_fifo_cap(S6_fifo_cap),
    .if_empty_n(S6_empty_n),
    .if_read(fft_stage_7_U0_S6_read)
);

fft_HW_fifo_w32_d2_S num_c30_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_stage_6_U0_num_c30_din),
    .if_full_n(num_c30_full_n),
    .if_write(fft_stage_6_U0_num_c30_write),
    .if_dout(num_c30_dout),
    .if_num_data_valid(num_c30_num_data_valid),
    .if_fifo_cap(num_c30_fifo_cap),
    .if_empty_n(num_c30_empty_n),
    .if_read(fft_stage_7_U0_numFFT_read)
);

fft_HW_fifo_w64_d1024_A S7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_stage_7_U0_S7_din),
    .if_full_n(S7_full_n),
    .if_write(fft_stage_7_U0_S7_write),
    .if_dout(S7_dout),
    .if_num_data_valid(S7_num_data_valid),
    .if_fifo_cap(S7_fifo_cap),
    .if_empty_n(S7_empty_n),
    .if_read(fft_stage_8_U0_S7_read)
);

fft_HW_fifo_w32_d2_S num_c29_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_stage_7_U0_num_c29_din),
    .if_full_n(num_c29_full_n),
    .if_write(fft_stage_7_U0_num_c29_write),
    .if_dout(num_c29_dout),
    .if_num_data_valid(num_c29_num_data_valid),
    .if_fifo_cap(num_c29_fifo_cap),
    .if_empty_n(num_c29_empty_n),
    .if_read(fft_stage_8_U0_numFFT_read)
);

fft_HW_fifo_w64_d1024_A S8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_stage_8_U0_S8_din),
    .if_full_n(S8_full_n),
    .if_write(fft_stage_8_U0_S8_write),
    .if_dout(S8_dout),
    .if_num_data_valid(S8_num_data_valid),
    .if_fifo_cap(S8_fifo_cap),
    .if_empty_n(S8_empty_n),
    .if_read(fft_stage_9_U0_S8_read)
);

fft_HW_fifo_w32_d2_S num_c28_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_stage_8_U0_num_c28_din),
    .if_full_n(num_c28_full_n),
    .if_write(fft_stage_8_U0_num_c28_write),
    .if_dout(num_c28_dout),
    .if_num_data_valid(num_c28_num_data_valid),
    .if_fifo_cap(num_c28_fifo_cap),
    .if_empty_n(num_c28_empty_n),
    .if_read(fft_stage_9_U0_numFFT_read)
);

fft_HW_fifo_w64_d1024_A S9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_stage_9_U0_S9_din),
    .if_full_n(S9_full_n),
    .if_write(fft_stage_9_U0_S9_write),
    .if_dout(S9_dout),
    .if_num_data_valid(S9_num_data_valid),
    .if_fifo_cap(S9_fifo_cap),
    .if_empty_n(S9_empty_n),
    .if_read(fft_stage_10_U0_S9_read)
);

fft_HW_fifo_w32_d2_S num_c27_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_stage_9_U0_num_c27_din),
    .if_full_n(num_c27_full_n),
    .if_write(fft_stage_9_U0_num_c27_write),
    .if_dout(num_c27_dout),
    .if_num_data_valid(num_c27_num_data_valid),
    .if_fifo_cap(num_c27_fifo_cap),
    .if_empty_n(num_c27_empty_n),
    .if_read(fft_stage_10_U0_numFFT_read)
);

fft_HW_fifo_w64_d1024_A S10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_stage_10_U0_S10_din),
    .if_full_n(S10_full_n),
    .if_write(fft_stage_10_U0_S10_write),
    .if_dout(S10_dout),
    .if_num_data_valid(S10_num_data_valid),
    .if_fifo_cap(S10_fifo_cap),
    .if_empty_n(S10_empty_n),
    .if_read(retrieve_nfft_value_U0_S10_read)
);

fft_HW_fifo_w32_d2_S num_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_stage_10_U0_num_c_din),
    .if_full_n(num_c_full_n),
    .if_write(fft_stage_10_U0_num_c_write),
    .if_dout(num_c_dout),
    .if_num_data_valid(num_c_num_data_valid),
    .if_fifo_cap(num_c_fifo_cap),
    .if_empty_n(num_c_empty_n),
    .if_read(retrieve_nfft_value_U0_numFFT_read)
);

fft_HW_start_for_retrieve_nfft_value_U0 start_for_retrieve_nfft_value_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_retrieve_nfft_value_U0_din),
    .if_full_n(start_for_retrieve_nfft_value_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_retrieve_nfft_value_U0_dout),
    .if_empty_n(start_for_retrieve_nfft_value_U0_empty_n),
    .if_read(retrieve_nfft_value_U0_ap_ready)
);

fft_HW_start_for_fft_stage_1_U0 start_for_fft_stage_1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fft_stage_1_U0_din),
    .if_full_n(start_for_fft_stage_1_U0_full_n),
    .if_write(load_nfft_value_U0_start_write),
    .if_dout(start_for_fft_stage_1_U0_dout),
    .if_empty_n(start_for_fft_stage_1_U0_empty_n),
    .if_read(fft_stage_1_U0_ap_ready)
);

fft_HW_start_for_fft_stage_2_U0 start_for_fft_stage_2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fft_stage_2_U0_din),
    .if_full_n(start_for_fft_stage_2_U0_full_n),
    .if_write(fft_stage_1_U0_start_write),
    .if_dout(start_for_fft_stage_2_U0_dout),
    .if_empty_n(start_for_fft_stage_2_U0_empty_n),
    .if_read(fft_stage_2_U0_ap_ready)
);

fft_HW_start_for_fft_stage_3_U0 start_for_fft_stage_3_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fft_stage_3_U0_din),
    .if_full_n(start_for_fft_stage_3_U0_full_n),
    .if_write(fft_stage_2_U0_start_write),
    .if_dout(start_for_fft_stage_3_U0_dout),
    .if_empty_n(start_for_fft_stage_3_U0_empty_n),
    .if_read(fft_stage_3_U0_ap_ready)
);

fft_HW_start_for_fft_stage_4_U0 start_for_fft_stage_4_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fft_stage_4_U0_din),
    .if_full_n(start_for_fft_stage_4_U0_full_n),
    .if_write(fft_stage_3_U0_start_write),
    .if_dout(start_for_fft_stage_4_U0_dout),
    .if_empty_n(start_for_fft_stage_4_U0_empty_n),
    .if_read(fft_stage_4_U0_ap_ready)
);

fft_HW_start_for_fft_stage_5_U0 start_for_fft_stage_5_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fft_stage_5_U0_din),
    .if_full_n(start_for_fft_stage_5_U0_full_n),
    .if_write(fft_stage_4_U0_start_write),
    .if_dout(start_for_fft_stage_5_U0_dout),
    .if_empty_n(start_for_fft_stage_5_U0_empty_n),
    .if_read(fft_stage_5_U0_ap_ready)
);

fft_HW_start_for_fft_stage_6_U0 start_for_fft_stage_6_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fft_stage_6_U0_din),
    .if_full_n(start_for_fft_stage_6_U0_full_n),
    .if_write(fft_stage_5_U0_start_write),
    .if_dout(start_for_fft_stage_6_U0_dout),
    .if_empty_n(start_for_fft_stage_6_U0_empty_n),
    .if_read(fft_stage_6_U0_ap_ready)
);

fft_HW_start_for_fft_stage_7_U0 start_for_fft_stage_7_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fft_stage_7_U0_din),
    .if_full_n(start_for_fft_stage_7_U0_full_n),
    .if_write(fft_stage_6_U0_start_write),
    .if_dout(start_for_fft_stage_7_U0_dout),
    .if_empty_n(start_for_fft_stage_7_U0_empty_n),
    .if_read(fft_stage_7_U0_ap_ready)
);

fft_HW_start_for_fft_stage_8_U0 start_for_fft_stage_8_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fft_stage_8_U0_din),
    .if_full_n(start_for_fft_stage_8_U0_full_n),
    .if_write(fft_stage_7_U0_start_write),
    .if_dout(start_for_fft_stage_8_U0_dout),
    .if_empty_n(start_for_fft_stage_8_U0_empty_n),
    .if_read(fft_stage_8_U0_ap_ready)
);

fft_HW_start_for_fft_stage_9_U0 start_for_fft_stage_9_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fft_stage_9_U0_din),
    .if_full_n(start_for_fft_stage_9_U0_full_n),
    .if_write(fft_stage_8_U0_start_write),
    .if_dout(start_for_fft_stage_9_U0_dout),
    .if_empty_n(start_for_fft_stage_9_U0_empty_n),
    .if_read(fft_stage_9_U0_ap_ready)
);

fft_HW_start_for_fft_stage_10_U0 start_for_fft_stage_10_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fft_stage_10_U0_din),
    .if_full_n(start_for_fft_stage_10_U0_full_n),
    .if_write(fft_stage_9_U0_start_write),
    .if_dout(start_for_fft_stage_10_U0_dout),
    .if_empty_n(start_for_fft_stage_10_U0_empty_n),
    .if_read(fft_stage_10_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_load_nfft_value_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_load_nfft_value_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_load_nfft_value_U0_ap_ready <= ap_sync_load_nfft_value_U0_ap_ready;
        end
    end
end

assign ap_done = retrieve_nfft_value_U0_ap_done;

assign ap_idle = (retrieve_nfft_value_U0_ap_idle & load_nfft_value_U0_ap_idle & fft_stage_9_U0_ap_idle & fft_stage_8_U0_ap_idle & fft_stage_7_U0_ap_idle & fft_stage_6_U0_ap_idle & fft_stage_5_U0_ap_idle & fft_stage_4_U0_ap_idle & fft_stage_3_U0_ap_idle & fft_stage_2_U0_ap_idle & fft_stage_1_U0_ap_idle & fft_stage_10_U0_ap_idle & entry_proc_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_load_nfft_value_U0_ap_ready = (load_nfft_value_U0_ap_ready | ap_sync_reg_load_nfft_value_U0_ap_ready);

assign ap_sync_ready = (ap_sync_load_nfft_value_U0_ap_ready & ap_sync_entry_proc_U0_ap_ready);

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign fft_stage_10_U0_ap_continue = 1'b1;

assign fft_stage_10_U0_ap_start = start_for_fft_stage_10_U0_empty_n;

assign fft_stage_1_U0_ap_continue = 1'b1;

assign fft_stage_1_U0_ap_start = start_for_fft_stage_1_U0_empty_n;

assign fft_stage_2_U0_ap_continue = 1'b1;

assign fft_stage_2_U0_ap_start = start_for_fft_stage_2_U0_empty_n;

assign fft_stage_3_U0_ap_continue = 1'b1;

assign fft_stage_3_U0_ap_start = start_for_fft_stage_3_U0_empty_n;

assign fft_stage_4_U0_ap_continue = 1'b1;

assign fft_stage_4_U0_ap_start = start_for_fft_stage_4_U0_empty_n;

assign fft_stage_5_U0_ap_continue = 1'b1;

assign fft_stage_5_U0_ap_start = start_for_fft_stage_5_U0_empty_n;

assign fft_stage_6_U0_ap_continue = 1'b1;

assign fft_stage_6_U0_ap_start = start_for_fft_stage_6_U0_empty_n;

assign fft_stage_7_U0_ap_continue = 1'b1;

assign fft_stage_7_U0_ap_start = start_for_fft_stage_7_U0_empty_n;

assign fft_stage_8_U0_ap_continue = 1'b1;

assign fft_stage_8_U0_ap_start = start_for_fft_stage_8_U0_empty_n;

assign fft_stage_9_U0_ap_continue = 1'b1;

assign fft_stage_9_U0_ap_start = start_for_fft_stage_9_U0_empty_n;

assign load_nfft_value_U0_ap_continue = 1'b1;

assign load_nfft_value_U0_ap_start = ((ap_sync_reg_load_nfft_value_U0_ap_ready ^ 1'b1) & ap_start);

assign m_axi_gmem_ARADDR = load_nfft_value_U0_m_axi_gmem_ARADDR;

assign m_axi_gmem_ARBURST = load_nfft_value_U0_m_axi_gmem_ARBURST;

assign m_axi_gmem_ARCACHE = load_nfft_value_U0_m_axi_gmem_ARCACHE;

assign m_axi_gmem_ARID = load_nfft_value_U0_m_axi_gmem_ARID;

assign m_axi_gmem_ARLEN = load_nfft_value_U0_m_axi_gmem_ARLEN;

assign m_axi_gmem_ARLOCK = load_nfft_value_U0_m_axi_gmem_ARLOCK;

assign m_axi_gmem_ARPROT = load_nfft_value_U0_m_axi_gmem_ARPROT;

assign m_axi_gmem_ARQOS = load_nfft_value_U0_m_axi_gmem_ARQOS;

assign m_axi_gmem_ARREGION = load_nfft_value_U0_m_axi_gmem_ARREGION;

assign m_axi_gmem_ARSIZE = load_nfft_value_U0_m_axi_gmem_ARSIZE;

assign m_axi_gmem_ARUSER = load_nfft_value_U0_m_axi_gmem_ARUSER;

assign m_axi_gmem_ARVALID = load_nfft_value_U0_m_axi_gmem_ARVALID;

assign m_axi_gmem_AWADDR = retrieve_nfft_value_U0_m_axi_gmem_AWADDR;

assign m_axi_gmem_AWBURST = retrieve_nfft_value_U0_m_axi_gmem_AWBURST;

assign m_axi_gmem_AWCACHE = retrieve_nfft_value_U0_m_axi_gmem_AWCACHE;

assign m_axi_gmem_AWID = retrieve_nfft_value_U0_m_axi_gmem_AWID;

assign m_axi_gmem_AWLEN = retrieve_nfft_value_U0_m_axi_gmem_AWLEN;

assign m_axi_gmem_AWLOCK = retrieve_nfft_value_U0_m_axi_gmem_AWLOCK;

assign m_axi_gmem_AWPROT = retrieve_nfft_value_U0_m_axi_gmem_AWPROT;

assign m_axi_gmem_AWQOS = retrieve_nfft_value_U0_m_axi_gmem_AWQOS;

assign m_axi_gmem_AWREGION = retrieve_nfft_value_U0_m_axi_gmem_AWREGION;

assign m_axi_gmem_AWSIZE = retrieve_nfft_value_U0_m_axi_gmem_AWSIZE;

assign m_axi_gmem_AWUSER = retrieve_nfft_value_U0_m_axi_gmem_AWUSER;

assign m_axi_gmem_AWVALID = retrieve_nfft_value_U0_m_axi_gmem_AWVALID;

assign m_axi_gmem_BREADY = retrieve_nfft_value_U0_m_axi_gmem_BREADY;

assign m_axi_gmem_RREADY = load_nfft_value_U0_m_axi_gmem_RREADY;

assign m_axi_gmem_WDATA = retrieve_nfft_value_U0_m_axi_gmem_WDATA;

assign m_axi_gmem_WID = retrieve_nfft_value_U0_m_axi_gmem_WID;

assign m_axi_gmem_WLAST = retrieve_nfft_value_U0_m_axi_gmem_WLAST;

assign m_axi_gmem_WSTRB = retrieve_nfft_value_U0_m_axi_gmem_WSTRB;

assign m_axi_gmem_WUSER = retrieve_nfft_value_U0_m_axi_gmem_WUSER;

assign m_axi_gmem_WVALID = retrieve_nfft_value_U0_m_axi_gmem_WVALID;

assign retrieve_nfft_value_U0_ap_continue = ap_continue;

assign retrieve_nfft_value_U0_ap_start = start_for_retrieve_nfft_value_U0_empty_n;

assign start_for_fft_stage_10_U0_din = 1'b1;

assign start_for_fft_stage_1_U0_din = 1'b1;

assign start_for_fft_stage_2_U0_din = 1'b1;

assign start_for_fft_stage_3_U0_din = 1'b1;

assign start_for_fft_stage_4_U0_din = 1'b1;

assign start_for_fft_stage_5_U0_din = 1'b1;

assign start_for_fft_stage_6_U0_din = 1'b1;

assign start_for_fft_stage_7_U0_din = 1'b1;

assign start_for_fft_stage_8_U0_din = 1'b1;

assign start_for_fft_stage_9_U0_din = 1'b1;

assign start_for_retrieve_nfft_value_U0_din = 1'b1;

endmodule //fft_HW_Top_DataFlox
