// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Processing_HW_Windowing (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Buff0_re_address0,
        Buff0_re_ce0,
        Buff0_re_q0,
        Buff0_im_address0,
        Buff0_im_ce0,
        Buff0_im_q0,
        Buff1_re_address0,
        Buff1_re_ce0,
        Buff1_re_q0,
        Buff1_im_address0,
        Buff1_im_ce0,
        Buff1_im_q0,
        Buff2_re_address0,
        Buff2_re_ce0,
        Buff2_re_q0,
        Buff2_im_address0,
        Buff2_im_ce0,
        Buff2_im_q0,
        Buff3_re_address0,
        Buff3_re_ce0,
        Buff3_re_we0,
        Buff3_re_d0,
        Buff3_re_q0,
        Buff3_im_address0,
        Buff3_im_ce0,
        Buff3_im_we0,
        Buff3_im_d0,
        Buff3_im_q0,
        D0_dout,
        D0_num_data_valid,
        D0_fifo_cap,
        D0_empty_n,
        D0_read,
        D1_din,
        D1_num_data_valid,
        D1_fifo_cap,
        D1_full_n,
        D1_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] Buff0_re_address0;
output   Buff0_re_ce0;
input  [31:0] Buff0_re_q0;
output  [9:0] Buff0_im_address0;
output   Buff0_im_ce0;
input  [31:0] Buff0_im_q0;
output  [9:0] Buff1_re_address0;
output   Buff1_re_ce0;
input  [31:0] Buff1_re_q0;
output  [9:0] Buff1_im_address0;
output   Buff1_im_ce0;
input  [31:0] Buff1_im_q0;
output  [9:0] Buff2_re_address0;
output   Buff2_re_ce0;
input  [31:0] Buff2_re_q0;
output  [9:0] Buff2_im_address0;
output   Buff2_im_ce0;
input  [31:0] Buff2_im_q0;
output  [9:0] Buff3_re_address0;
output   Buff3_re_ce0;
output   Buff3_re_we0;
output  [31:0] Buff3_re_d0;
input  [31:0] Buff3_re_q0;
output  [9:0] Buff3_im_address0;
output   Buff3_im_ce0;
output   Buff3_im_we0;
output  [31:0] Buff3_im_d0;
input  [31:0] Buff3_im_q0;
input  [63:0] D0_dout;
input  [10:0] D0_num_data_valid;
input  [10:0] D0_fifo_cap;
input   D0_empty_n;
output   D0_read;
output  [63:0] D1_din;
input  [10:0] D1_num_data_valid;
input  [10:0] D1_fifo_cap;
input   D1_full_n;
output   D1_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[9:0] Buff3_re_address0;
reg Buff3_re_ce0;
reg Buff3_re_we0;
reg[9:0] Buff3_im_address0;
reg Buff3_im_ce0;
reg Buff3_im_we0;
reg D0_read;
reg D1_write;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_ap_start;
wire    grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_ap_done;
wire    grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_ap_idle;
wire    grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_ap_ready;
wire    grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_D0_read;
wire   [9:0] grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_Buff3_re_address0;
wire    grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_Buff3_re_ce0;
wire    grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_Buff3_re_we0;
wire   [31:0] grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_Buff3_re_d0;
wire   [9:0] grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_Buff3_im_address0;
wire    grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_Buff3_im_ce0;
wire    grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_Buff3_im_we0;
wire   [31:0] grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_Buff3_im_d0;
wire    grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_ap_start;
wire    grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_ap_done;
wire    grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_ap_idle;
wire    grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_ap_ready;
wire   [63:0] grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_D1_din;
wire    grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_D1_write;
wire   [9:0] grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff0_re_address0;
wire    grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff0_re_ce0;
wire   [9:0] grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff0_im_address0;
wire    grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff0_im_ce0;
wire   [9:0] grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff1_re_address0;
wire    grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff1_re_ce0;
wire   [9:0] grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff1_im_address0;
wire    grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff1_im_ce0;
wire   [9:0] grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff2_re_address0;
wire    grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff2_re_ce0;
wire   [9:0] grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff2_im_address0;
wire    grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff2_im_ce0;
wire   [9:0] grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff3_re_address0;
wire    grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff3_re_ce0;
wire   [9:0] grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff3_im_address0;
wire    grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff3_im_ce0;
reg    grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_ap_start_reg = 1'b0;
#0 grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_ap_start_reg = 1'b0;
end

Processing_HW_Windowing_Pipeline_VITIS_LOOP_5637_1 grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_ap_start),
    .ap_done(grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_ap_done),
    .ap_idle(grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_ap_idle),
    .ap_ready(grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_ap_ready),
    .D0_dout(D0_dout),
    .D0_num_data_valid(11'd0),
    .D0_fifo_cap(11'd0),
    .D0_empty_n(D0_empty_n),
    .D0_read(grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_D0_read),
    .Buff3_re_address0(grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_Buff3_re_address0),
    .Buff3_re_ce0(grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_Buff3_re_ce0),
    .Buff3_re_we0(grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_Buff3_re_we0),
    .Buff3_re_d0(grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_Buff3_re_d0),
    .Buff3_im_address0(grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_Buff3_im_address0),
    .Buff3_im_ce0(grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_Buff3_im_ce0),
    .Buff3_im_we0(grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_Buff3_im_we0),
    .Buff3_im_d0(grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_Buff3_im_d0)
);

Processing_HW_Windowing_Pipeline_VITIS_LOOP_5641_2 grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_ap_start),
    .ap_done(grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_ap_done),
    .ap_idle(grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_ap_idle),
    .ap_ready(grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_ap_ready),
    .D1_din(grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_D1_din),
    .D1_num_data_valid(11'd0),
    .D1_fifo_cap(11'd0),
    .D1_full_n(D1_full_n),
    .D1_write(grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_D1_write),
    .Buff0_re_address0(grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff0_re_address0),
    .Buff0_re_ce0(grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff0_re_ce0),
    .Buff0_re_q0(Buff0_re_q0),
    .Buff0_im_address0(grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff0_im_address0),
    .Buff0_im_ce0(grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff0_im_ce0),
    .Buff0_im_q0(Buff0_im_q0),
    .Buff1_re_address0(grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff1_re_address0),
    .Buff1_re_ce0(grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff1_re_ce0),
    .Buff1_re_q0(Buff1_re_q0),
    .Buff1_im_address0(grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff1_im_address0),
    .Buff1_im_ce0(grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff1_im_ce0),
    .Buff1_im_q0(Buff1_im_q0),
    .Buff2_re_address0(grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff2_re_address0),
    .Buff2_re_ce0(grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff2_re_ce0),
    .Buff2_re_q0(Buff2_re_q0),
    .Buff2_im_address0(grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff2_im_address0),
    .Buff2_im_ce0(grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff2_im_ce0),
    .Buff2_im_q0(Buff2_im_q0),
    .Buff3_re_address0(grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff3_re_address0),
    .Buff3_re_ce0(grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff3_re_ce0),
    .Buff3_re_q0(Buff3_re_q0),
    .Buff3_im_address0(grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff3_im_address0),
    .Buff3_im_ce0(grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff3_im_ce0),
    .Buff3_im_q0(Buff3_im_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_ap_start_reg <= 1'b1;
        end else if ((grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_ap_ready == 1'b1)) begin
            grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_ap_start_reg <= 1'b1;
        end else if ((grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_ap_ready == 1'b1)) begin
            grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        Buff3_im_address0 = grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff3_im_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        Buff3_im_address0 = grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_Buff3_im_address0;
    end else begin
        Buff3_im_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        Buff3_im_ce0 = grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff3_im_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        Buff3_im_ce0 = grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_Buff3_im_ce0;
    end else begin
        Buff3_im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Buff3_im_we0 = grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_Buff3_im_we0;
    end else begin
        Buff3_im_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        Buff3_re_address0 = grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff3_re_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        Buff3_re_address0 = grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_Buff3_re_address0;
    end else begin
        Buff3_re_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        Buff3_re_ce0 = grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff3_re_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        Buff3_re_ce0 = grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_Buff3_re_ce0;
    end else begin
        Buff3_re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Buff3_re_we0 = grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_Buff3_re_we0;
    end else begin
        Buff3_re_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        D0_read = grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_D0_read;
    end else begin
        D0_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        D1_write = grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_D1_write;
    end else begin
        D1_write = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_state5) & (grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_ap_done == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Buff0_im_address0 = grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff0_im_address0;

assign Buff0_im_ce0 = grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff0_im_ce0;

assign Buff0_re_address0 = grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff0_re_address0;

assign Buff0_re_ce0 = grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff0_re_ce0;

assign Buff1_im_address0 = grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff1_im_address0;

assign Buff1_im_ce0 = grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff1_im_ce0;

assign Buff1_re_address0 = grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff1_re_address0;

assign Buff1_re_ce0 = grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff1_re_ce0;

assign Buff2_im_address0 = grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff2_im_address0;

assign Buff2_im_ce0 = grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff2_im_ce0;

assign Buff2_re_address0 = grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff2_re_address0;

assign Buff2_re_ce0 = grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_Buff2_re_ce0;

assign Buff3_im_d0 = grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_Buff3_im_d0;

assign Buff3_re_d0 = grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_Buff3_re_d0;

assign D1_din = grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_D1_din;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_ap_start = grp_Windowing_Pipeline_VITIS_LOOP_5637_1_fu_46_ap_start_reg;

assign grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_ap_start = grp_Windowing_Pipeline_VITIS_LOOP_5641_2_fu_56_ap_start_reg;

endmodule //Processing_HW_Windowing
