// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fft_HW_load_nfft_value (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        in_r,
        S0_din,
        S0_num_data_valid,
        S0_fifo_cap,
        S0_full_n,
        S0_write,
        numFFT,
        num_c36_din,
        num_c36_num_data_valid,
        num_c36_fifo_cap,
        num_c36_full_n,
        num_c36_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [63:0] m_axi_gmem0_WDATA;
output  [7:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [63:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [9:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [63:0] in_r;
output  [63:0] S0_din;
input  [10:0] S0_num_data_valid;
input  [10:0] S0_fifo_cap;
input   S0_full_n;
output   S0_write;
input  [31:0] numFFT;
output  [31:0] num_c36_din;
input  [1:0] num_c36_num_data_valid;
input  [1:0] num_c36_fifo_cap;
input   num_c36_full_n;
output   num_c36_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg m_axi_gmem0_ARVALID;
reg m_axi_gmem0_RREADY;
reg S0_write;
reg num_c36_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    num_c36_blk_n;
wire   [5:0] shl_ln_fu_137_p3;
reg   [5:0] shl_ln_reg_210;
wire   [5:0] shl_ln76_1_fu_145_p3;
reg   [5:0] shl_ln76_1_reg_215;
reg   [31:0] counter_V_1_reg_220;
wire    ap_CS_fsm_state2;
wire   [42:0] or_ln186_fu_181_p2;
reg   [42:0] or_ln186_reg_228;
wire   [0:0] icmp_ln1027_fu_162_p2;
reg   [9:0] BufferIN_re_address0;
reg    BufferIN_re_ce0;
reg    BufferIN_re_we0;
wire   [31:0] BufferIN_re_q0;
reg   [9:0] BufferIN_im_address0;
reg    BufferIN_im_ce0;
reg    BufferIN_im_we0;
wire   [31:0] BufferIN_im_q0;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_ap_start;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_ap_done;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_ap_idle;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_ap_ready;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_AWVALID;
wire   [63:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_AWADDR;
wire   [0:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_AWID;
wire   [31:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_AWLEN;
wire   [2:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_AWSIZE;
wire   [1:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_AWBURST;
wire   [1:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_AWLOCK;
wire   [3:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_AWCACHE;
wire   [2:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_AWPROT;
wire   [3:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_AWQOS;
wire   [3:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_AWREGION;
wire   [0:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_AWUSER;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_WVALID;
wire   [63:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_WDATA;
wire   [7:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_WSTRB;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_WLAST;
wire   [0:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_WID;
wire   [0:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_WUSER;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARVALID;
wire   [63:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARADDR;
wire   [0:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARID;
wire   [31:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARLEN;
wire   [2:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARSIZE;
wire   [1:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARBURST;
wire   [1:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARLOCK;
wire   [3:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARCACHE;
wire   [2:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARPROT;
wire   [3:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARQOS;
wire   [3:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARREGION;
wire   [0:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARUSER;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_RREADY;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_BREADY;
wire   [9:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_BufferIN_re_address0;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_BufferIN_re_ce0;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_BufferIN_re_we0;
wire   [31:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_BufferIN_re_d0;
wire   [9:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_BufferIN_im_address0;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_BufferIN_im_ce0;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_BufferIN_im_we0;
wire   [31:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_BufferIN_im_d0;
wire    grp_load_nfft_value_Pipeline_load_total_fu_119_ap_start;
wire    grp_load_nfft_value_Pipeline_load_total_fu_119_ap_done;
wire    grp_load_nfft_value_Pipeline_load_total_fu_119_ap_idle;
wire    grp_load_nfft_value_Pipeline_load_total_fu_119_ap_ready;
wire   [63:0] grp_load_nfft_value_Pipeline_load_total_fu_119_S0_din;
wire    grp_load_nfft_value_Pipeline_load_total_fu_119_S0_write;
wire   [9:0] grp_load_nfft_value_Pipeline_load_total_fu_119_BufferIN_re_address0;
wire    grp_load_nfft_value_Pipeline_load_total_fu_119_BufferIN_re_ce0;
wire   [9:0] grp_load_nfft_value_Pipeline_load_total_fu_119_BufferIN_im_address0;
wire    grp_load_nfft_value_Pipeline_load_total_fu_119_BufferIN_im_ce0;
reg    grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    grp_load_nfft_value_Pipeline_load_total_fu_119_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [31:0] counter_V_fu_74;
wire   [31:0] add_ln840_fu_167_p2;
reg    ap_block_state1;
wire   [2:0] trunc_ln95_fu_127_p1;
wire   [2:0] xor_ln95_fu_131_p2;
wire   [42:0] shl_ln1_fu_173_p3;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_ap_start_reg = 1'b0;
#0 grp_load_nfft_value_Pipeline_load_total_fu_119_ap_start_reg = 1'b0;
end

fft_HW_load_nfft_value_BufferIN_re_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
BufferIN_re_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(BufferIN_re_address0),
    .ce0(BufferIN_re_ce0),
    .we0(BufferIN_re_we0),
    .d0(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_BufferIN_re_d0),
    .q0(BufferIN_re_q0)
);

fft_HW_load_nfft_value_BufferIN_re_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
BufferIN_im_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(BufferIN_im_address0),
    .ce0(BufferIN_im_ce0),
    .we0(BufferIN_im_we0),
    .d0(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_BufferIN_im_d0),
    .q0(BufferIN_im_q0)
);

fft_HW_load_nfft_value_Pipeline_VITIS_LOOP_97_1 grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_ap_start),
    .ap_done(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_ap_done),
    .ap_idle(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_ap_idle),
    .ap_ready(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_ap_ready),
    .m_axi_gmem0_AWVALID(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(m_axi_gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(m_axi_gmem0_RVALID),
    .m_axi_gmem0_RREADY(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(m_axi_gmem0_RDATA),
    .m_axi_gmem0_RLAST(m_axi_gmem0_RLAST),
    .m_axi_gmem0_RID(m_axi_gmem0_RID),
    .m_axi_gmem0_RFIFONUM(m_axi_gmem0_RFIFONUM),
    .m_axi_gmem0_RUSER(m_axi_gmem0_RUSER),
    .m_axi_gmem0_RRESP(m_axi_gmem0_RRESP),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .BufferIN_re_address0(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_BufferIN_re_address0),
    .BufferIN_re_ce0(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_BufferIN_re_ce0),
    .BufferIN_re_we0(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_BufferIN_re_we0),
    .BufferIN_re_d0(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_BufferIN_re_d0),
    .BufferIN_im_address0(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_BufferIN_im_address0),
    .BufferIN_im_ce0(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_BufferIN_im_ce0),
    .BufferIN_im_we0(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_BufferIN_im_we0),
    .BufferIN_im_d0(grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_BufferIN_im_d0),
    .counter_V(counter_V_1_reg_220),
    .in_r(in_r),
    .zext_ln76(shl_ln_reg_210),
    .or_ln186(or_ln186_reg_228),
    .zext_ln95(shl_ln76_1_reg_215)
);

fft_HW_load_nfft_value_Pipeline_load_total grp_load_nfft_value_Pipeline_load_total_fu_119(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_load_nfft_value_Pipeline_load_total_fu_119_ap_start),
    .ap_done(grp_load_nfft_value_Pipeline_load_total_fu_119_ap_done),
    .ap_idle(grp_load_nfft_value_Pipeline_load_total_fu_119_ap_idle),
    .ap_ready(grp_load_nfft_value_Pipeline_load_total_fu_119_ap_ready),
    .S0_din(grp_load_nfft_value_Pipeline_load_total_fu_119_S0_din),
    .S0_num_data_valid(11'd0),
    .S0_fifo_cap(11'd0),
    .S0_full_n(S0_full_n),
    .S0_write(grp_load_nfft_value_Pipeline_load_total_fu_119_S0_write),
    .BufferIN_re_address0(grp_load_nfft_value_Pipeline_load_total_fu_119_BufferIN_re_address0),
    .BufferIN_re_ce0(grp_load_nfft_value_Pipeline_load_total_fu_119_BufferIN_re_ce0),
    .BufferIN_re_q0(BufferIN_re_q0),
    .BufferIN_im_address0(grp_load_nfft_value_Pipeline_load_total_fu_119_BufferIN_im_address0),
    .BufferIN_im_ce0(grp_load_nfft_value_Pipeline_load_total_fu_119_BufferIN_im_ce0),
    .BufferIN_im_q0(BufferIN_im_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1027_fu_162_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1027_fu_162_p2 == 1'd0))) begin
            grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_ap_start_reg <= 1'b1;
        end else if ((grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_ap_ready == 1'b1)) begin
            grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_load_nfft_value_Pipeline_load_total_fu_119_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_load_nfft_value_Pipeline_load_total_fu_119_ap_start_reg <= 1'b1;
        end else if ((grp_load_nfft_value_Pipeline_load_total_fu_119_ap_ready == 1'b1)) begin
            grp_load_nfft_value_Pipeline_load_total_fu_119_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | (num_c36_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        counter_V_fu_74 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1027_fu_162_p2 == 1'd0))) begin
        counter_V_fu_74 <= add_ln840_fu_167_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        counter_V_1_reg_220 <= counter_V_fu_74;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1027_fu_162_p2 == 1'd0))) begin
        or_ln186_reg_228[42 : 11] <= or_ln186_fu_181_p2[42 : 11];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        shl_ln76_1_reg_215[5 : 3] <= shl_ln76_1_fu_145_p3[5 : 3];
        shl_ln_reg_210[5 : 3] <= shl_ln_fu_137_p3[5 : 3];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        BufferIN_im_address0 = grp_load_nfft_value_Pipeline_load_total_fu_119_BufferIN_im_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        BufferIN_im_address0 = grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_BufferIN_im_address0;
    end else begin
        BufferIN_im_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        BufferIN_im_ce0 = grp_load_nfft_value_Pipeline_load_total_fu_119_BufferIN_im_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        BufferIN_im_ce0 = grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_BufferIN_im_ce0;
    end else begin
        BufferIN_im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        BufferIN_im_we0 = grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_BufferIN_im_we0;
    end else begin
        BufferIN_im_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        BufferIN_re_address0 = grp_load_nfft_value_Pipeline_load_total_fu_119_BufferIN_re_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        BufferIN_re_address0 = grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_BufferIN_re_address0;
    end else begin
        BufferIN_re_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        BufferIN_re_ce0 = grp_load_nfft_value_Pipeline_load_total_fu_119_BufferIN_re_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        BufferIN_re_ce0 = grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_BufferIN_re_ce0;
    end else begin
        BufferIN_re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        BufferIN_re_we0 = grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_BufferIN_re_we0;
    end else begin
        BufferIN_re_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        S0_write = grp_load_nfft_value_Pipeline_load_total_fu_119_S0_write;
    end else begin
        S0_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0) | (num_c36_full_n == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_load_nfft_value_Pipeline_load_total_fu_119_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1027_fu_162_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1027_fu_162_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln1027_fu_162_p2 == 1'd0)))) begin
        m_axi_gmem0_ARVALID = grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARVALID;
    end else begin
        m_axi_gmem0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln1027_fu_162_p2 == 1'd0)))) begin
        m_axi_gmem0_RREADY = grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_RREADY;
    end else begin
        m_axi_gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        num_c36_blk_n = num_c36_full_n;
    end else begin
        num_c36_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | (num_c36_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        num_c36_write = 1'b1;
    end else begin
        num_c36_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | (num_c36_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1027_fu_162_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_load_nfft_value_Pipeline_load_total_fu_119_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign S0_din = grp_load_nfft_value_Pipeline_load_total_fu_119_S0_din;

assign add_ln840_fu_167_p2 = (counter_V_fu_74 + 32'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0) | (num_c36_full_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_ap_start = grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_ap_start_reg;

assign grp_load_nfft_value_Pipeline_load_total_fu_119_ap_start = grp_load_nfft_value_Pipeline_load_total_fu_119_ap_start_reg;

assign icmp_ln1027_fu_162_p2 = ((counter_V_fu_74 == numFFT) ? 1'b1 : 1'b0);

assign m_axi_gmem0_ARADDR = grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARADDR;

assign m_axi_gmem0_ARBURST = grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARBURST;

assign m_axi_gmem0_ARCACHE = grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARCACHE;

assign m_axi_gmem0_ARID = grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARID;

assign m_axi_gmem0_ARLEN = grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARLEN;

assign m_axi_gmem0_ARLOCK = grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARLOCK;

assign m_axi_gmem0_ARPROT = grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARPROT;

assign m_axi_gmem0_ARQOS = grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARQOS;

assign m_axi_gmem0_ARREGION = grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARREGION;

assign m_axi_gmem0_ARSIZE = grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARSIZE;

assign m_axi_gmem0_ARUSER = grp_load_nfft_value_Pipeline_VITIS_LOOP_97_1_fu_106_m_axi_gmem0_ARUSER;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_WDATA = 64'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 8'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign num_c36_din = numFFT;

assign or_ln186_fu_181_p2 = (shl_ln1_fu_173_p3 | 43'd1);

assign shl_ln1_fu_173_p3 = {{counter_V_fu_74}, {11'd0}};

assign shl_ln76_1_fu_145_p3 = {{xor_ln95_fu_131_p2}, {3'd0}};

assign shl_ln_fu_137_p3 = {{trunc_ln95_fu_127_p1}, {3'd0}};

assign start_out = real_start;

assign trunc_ln95_fu_127_p1 = in_r[2:0];

assign xor_ln95_fu_131_p2 = (trunc_ln95_fu_127_p1 ^ 3'd4);

always @ (posedge ap_clk) begin
    shl_ln_reg_210[2:0] <= 3'b000;
    shl_ln76_1_reg_215[2:0] <= 3'b000;
    or_ln186_reg_228[10:0] <= 11'b00000000001;
end

endmodule //fft_HW_load_nfft_value
