// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fft_HW_load_nfft_value (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        in_r,
        S0_din,
        S0_num_data_valid,
        S0_fifo_cap,
        S0_full_n,
        S0_write,
        numFFT,
        num_c36_din,
        num_c36_num_data_valid,
        num_c36_fifo_cap,
        num_c36_full_n,
        num_c36_write
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [63:0] m_axi_gmem_WDATA;
output  [7:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [63:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [8:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [63:0] in_r;
output  [63:0] S0_din;
input  [10:0] S0_num_data_valid;
input  [10:0] S0_fifo_cap;
input   S0_full_n;
output   S0_write;
input  [31:0] numFFT;
output  [31:0] num_c36_din;
input  [1:0] num_c36_num_data_valid;
input  [1:0] num_c36_fifo_cap;
input   num_c36_full_n;
output   num_c36_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg m_axi_gmem_ARVALID;
reg[63:0] m_axi_gmem_ARADDR;
reg[0:0] m_axi_gmem_ARID;
reg[31:0] m_axi_gmem_ARLEN;
reg[2:0] m_axi_gmem_ARSIZE;
reg[1:0] m_axi_gmem_ARBURST;
reg[1:0] m_axi_gmem_ARLOCK;
reg[3:0] m_axi_gmem_ARCACHE;
reg[2:0] m_axi_gmem_ARPROT;
reg[3:0] m_axi_gmem_ARQOS;
reg[3:0] m_axi_gmem_ARREGION;
reg[0:0] m_axi_gmem_ARUSER;
reg m_axi_gmem_RREADY;
reg S0_write;
reg num_c36_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    gmem_blk_n_AR;
reg    num_c36_blk_n;
wire   [31:0] shl_ln119_fu_123_p2;
wire  signed [60:0] trunc_ln_fu_130_p4;
reg   [60:0] trunc_ln_reg_192;
reg   [8:0] BufferIN_V_address0;
reg    BufferIN_V_ce0;
reg    BufferIN_V_we0;
wire   [63:0] BufferIN_V_q0;
reg   [8:0] BufferIN_V_1_address0;
reg    BufferIN_V_1_ce0;
reg    BufferIN_V_1_we0;
wire   [63:0] BufferIN_V_1_q0;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_ap_start;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_ap_done;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_ap_idle;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_ap_ready;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_AWVALID;
wire   [63:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_AWADDR;
wire   [0:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_AWID;
wire   [31:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_AWLEN;
wire   [2:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_AWSIZE;
wire   [1:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_AWBURST;
wire   [1:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_AWLOCK;
wire   [3:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_AWCACHE;
wire   [2:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_AWPROT;
wire   [3:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_AWQOS;
wire   [3:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_AWREGION;
wire   [0:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_AWUSER;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_WVALID;
wire   [63:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_WDATA;
wire   [7:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_WSTRB;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_WLAST;
wire   [0:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_WID;
wire   [0:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_WUSER;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARVALID;
wire   [63:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARADDR;
wire   [0:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARID;
wire   [31:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARLEN;
wire   [2:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARSIZE;
wire   [1:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARBURST;
wire   [1:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARLOCK;
wire   [3:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARCACHE;
wire   [2:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARPROT;
wire   [3:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARQOS;
wire   [3:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARREGION;
wire   [0:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARUSER;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_RREADY;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_BREADY;
wire   [8:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_BufferIN_V_1_address0;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_BufferIN_V_1_ce0;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_BufferIN_V_1_we0;
wire   [63:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_BufferIN_V_1_d0;
wire   [8:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_BufferIN_V_address0;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_BufferIN_V_ce0;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_BufferIN_V_we0;
wire   [63:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_BufferIN_V_d0;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_ap_start;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_ap_done;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_ap_idle;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_ap_ready;
wire   [63:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_S0_din;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_S0_write;
wire   [8:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_BufferIN_V_address0;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_BufferIN_V_ce0;
wire   [8:0] grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_BufferIN_V_1_address0;
wire    grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_BufferIN_V_1_ce0;
reg    grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_ap_start_reg;
wire    ap_CS_fsm_state8;
wire   [0:0] icmp_ln1027_fu_159_p2;
wire    ap_CS_fsm_state9;
reg    grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire  signed [63:0] sext_ln119_fu_140_p1;
reg    ap_block_state1;
reg   [31:0] counter_V_fu_68;
wire   [31:0] add_ln840_fu_164_p2;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 11'd1;
#0 grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_ap_start_reg = 1'b0;
#0 grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_ap_start_reg = 1'b0;
end

fft_HW_load_nfft_value_BufferIN_V_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
BufferIN_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(BufferIN_V_address0),
    .ce0(BufferIN_V_ce0),
    .we0(BufferIN_V_we0),
    .d0(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_BufferIN_V_d0),
    .q0(BufferIN_V_q0)
);

fft_HW_load_nfft_value_BufferIN_V_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
BufferIN_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(BufferIN_V_1_address0),
    .ce0(BufferIN_V_1_ce0),
    .we0(BufferIN_V_1_we0),
    .d0(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_BufferIN_V_1_d0),
    .q0(BufferIN_V_1_q0)
);

fft_HW_load_nfft_value_Pipeline_VITIS_LOOP_121_2 grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_ap_start),
    .ap_done(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_ap_done),
    .ap_idle(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_ap_idle),
    .ap_ready(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_ap_ready),
    .m_axi_gmem_AWVALID(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(m_axi_gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(m_axi_gmem_RVALID),
    .m_axi_gmem_RREADY(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(m_axi_gmem_RDATA),
    .m_axi_gmem_RLAST(m_axi_gmem_RLAST),
    .m_axi_gmem_RID(m_axi_gmem_RID),
    .m_axi_gmem_RFIFONUM(m_axi_gmem_RFIFONUM),
    .m_axi_gmem_RUSER(m_axi_gmem_RUSER),
    .m_axi_gmem_RRESP(m_axi_gmem_RRESP),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .sext_ln119(trunc_ln_reg_192),
    .BufferIN_V_1_address0(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_BufferIN_V_1_address0),
    .BufferIN_V_1_ce0(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_BufferIN_V_1_ce0),
    .BufferIN_V_1_we0(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_BufferIN_V_1_we0),
    .BufferIN_V_1_d0(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_BufferIN_V_1_d0),
    .BufferIN_V_address0(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_BufferIN_V_address0),
    .BufferIN_V_ce0(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_BufferIN_V_ce0),
    .BufferIN_V_we0(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_BufferIN_V_we0),
    .BufferIN_V_d0(grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_BufferIN_V_d0)
);

fft_HW_load_nfft_value_Pipeline_VITIS_LOOP_126_3 grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_ap_start),
    .ap_done(grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_ap_done),
    .ap_idle(grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_ap_idle),
    .ap_ready(grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_ap_ready),
    .S0_din(grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_S0_din),
    .S0_num_data_valid(11'd0),
    .S0_fifo_cap(11'd0),
    .S0_full_n(S0_full_n),
    .S0_write(grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_S0_write),
    .BufferIN_V_address0(grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_BufferIN_V_address0),
    .BufferIN_V_ce0(grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_BufferIN_V_ce0),
    .BufferIN_V_q0(BufferIN_V_q0),
    .BufferIN_V_1_address0(grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_BufferIN_V_1_address0),
    .BufferIN_V_1_ce0(grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_BufferIN_V_1_ce0),
    .BufferIN_V_1_q0(BufferIN_V_1_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln1027_fu_159_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln1027_fu_159_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
            grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_ap_start_reg <= 1'b1;
        end else if ((grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_ap_ready == 1'b1)) begin
            grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_ap_start_reg <= 1'b1;
        end else if ((grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_ap_ready == 1'b1)) begin
            grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((m_axi_gmem_ARREADY == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0) | (num_c36_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        counter_V_fu_68 <= 32'd0;
    end else if (((icmp_ln1027_fu_159_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        counter_V_fu_68 <= add_ln840_fu_164_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        trunc_ln_reg_192 <= {{in_r[63:3]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        BufferIN_V_1_address0 = grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_BufferIN_V_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        BufferIN_V_1_address0 = grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_BufferIN_V_1_address0;
    end else begin
        BufferIN_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        BufferIN_V_1_ce0 = grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_BufferIN_V_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        BufferIN_V_1_ce0 = grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_BufferIN_V_1_ce0;
    end else begin
        BufferIN_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        BufferIN_V_1_we0 = grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_BufferIN_V_1_we0;
    end else begin
        BufferIN_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        BufferIN_V_address0 = grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_BufferIN_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        BufferIN_V_address0 = grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_BufferIN_V_address0;
    end else begin
        BufferIN_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        BufferIN_V_ce0 = grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_BufferIN_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        BufferIN_V_ce0 = grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_BufferIN_V_ce0;
    end else begin
        BufferIN_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        BufferIN_V_we0 = grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_BufferIN_V_we0;
    end else begin
        BufferIN_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        S0_write = grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_S0_write;
    end else begin
        S0_write = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_ARREADY == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0) | (num_c36_full_n == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1027_fu_159_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln1027_fu_159_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((m_axi_gmem_ARREADY == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0) | (num_c36_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_gmem_ARADDR = sext_ln119_fu_140_p1;
    end else if (((1'b1 == ap_CS_fsm_state9) | ((icmp_ln1027_fu_159_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8)))) begin
        m_axi_gmem_ARADDR = grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARADDR;
    end else begin
        m_axi_gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((icmp_ln1027_fu_159_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8)))) begin
        m_axi_gmem_ARBURST = grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARBURST;
    end else begin
        m_axi_gmem_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((icmp_ln1027_fu_159_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8)))) begin
        m_axi_gmem_ARCACHE = grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARCACHE;
    end else begin
        m_axi_gmem_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((icmp_ln1027_fu_159_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8)))) begin
        m_axi_gmem_ARID = grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARID;
    end else begin
        m_axi_gmem_ARID = 1'd0;
    end
end

always @ (*) begin
    if ((~((m_axi_gmem_ARREADY == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0) | (num_c36_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_gmem_ARLEN = shl_ln119_fu_123_p2;
    end else if (((1'b1 == ap_CS_fsm_state9) | ((icmp_ln1027_fu_159_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8)))) begin
        m_axi_gmem_ARLEN = grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARLEN;
    end else begin
        m_axi_gmem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((icmp_ln1027_fu_159_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8)))) begin
        m_axi_gmem_ARLOCK = grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARLOCK;
    end else begin
        m_axi_gmem_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((icmp_ln1027_fu_159_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8)))) begin
        m_axi_gmem_ARPROT = grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARPROT;
    end else begin
        m_axi_gmem_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((icmp_ln1027_fu_159_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8)))) begin
        m_axi_gmem_ARQOS = grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARQOS;
    end else begin
        m_axi_gmem_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((icmp_ln1027_fu_159_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8)))) begin
        m_axi_gmem_ARREGION = grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARREGION;
    end else begin
        m_axi_gmem_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((icmp_ln1027_fu_159_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8)))) begin
        m_axi_gmem_ARSIZE = grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARSIZE;
    end else begin
        m_axi_gmem_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((icmp_ln1027_fu_159_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8)))) begin
        m_axi_gmem_ARUSER = grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARUSER;
    end else begin
        m_axi_gmem_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if ((~((m_axi_gmem_ARREADY == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0) | (num_c36_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_gmem_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state9) | ((icmp_ln1027_fu_159_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8)))) begin
        m_axi_gmem_ARVALID = grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_ARVALID;
    end else begin
        m_axi_gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((icmp_ln1027_fu_159_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8)))) begin
        m_axi_gmem_RREADY = grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_m_axi_gmem_RREADY;
    end else begin
        m_axi_gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        num_c36_blk_n = num_c36_full_n;
    end else begin
        num_c36_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((m_axi_gmem_ARREADY == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0) | (num_c36_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        num_c36_write = 1'b1;
    end else begin
        num_c36_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((m_axi_gmem_ARREADY == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0) | (num_c36_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((icmp_ln1027_fu_159_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign S0_din = grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_S0_din;

assign add_ln840_fu_164_p2 = (counter_V_fu_68 + 32'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0) | (num_c36_full_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_ap_start = grp_load_nfft_value_Pipeline_VITIS_LOOP_121_2_fu_106_ap_start_reg;

assign grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_ap_start = grp_load_nfft_value_Pipeline_VITIS_LOOP_126_3_fu_115_ap_start_reg;

assign icmp_ln1027_fu_159_p2 = ((counter_V_fu_68 == numFFT) ? 1'b1 : 1'b0);

assign m_axi_gmem_AWADDR = 64'd0;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd0;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_AWVALID = 1'b0;

assign m_axi_gmem_BREADY = 1'b0;

assign m_axi_gmem_WDATA = 64'd0;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 8'd0;

assign m_axi_gmem_WUSER = 1'd0;

assign m_axi_gmem_WVALID = 1'b0;

assign num_c36_din = numFFT;

assign sext_ln119_fu_140_p1 = trunc_ln_fu_130_p4;

assign shl_ln119_fu_123_p2 = numFFT << 32'd10;

assign start_out = real_start;

assign trunc_ln_fu_130_p4 = {{in_r[63:3]}};

endmodule //fft_HW_load_nfft_value
